### PR TITLE
Displayed images posted by a user on their profile page #86

### LINKED ISSUE #86: Display all the images posted by a user on their profile page
**Description**
All images posted by a user should appear on their profile page.

**Objectives**
- Create a grid component for the images on the profile page
- Fetch images posted by a user from the backend and display on the frontend

**Frontend**
- Edit CSS for the displayed user images

**Backend**
- Create a GetUserImages function in ImageService.cs in order to return user images with a specified user ID
- Create endpoint in public controller that returns the images

### PR DESCRIPTION
**Pull request by salehatrq**
Closes #86

### CODE REVIEW

**Review by AliZ786 — APPROVED** [review]
Well done. Looks very nice!

**Review by ChristopherKhoury — APPROVED** [review]
Looks great!

**Review by GryPr — APPROVED** [review]
LGTM!

Merge the changes whenever you're ready @salehatrq

**Comment by GryPr** [comment]
Merged master into your branch to fix the conflict issues

**Pull request merged**
