### PR TITLE
Format README.md and add names to team list

### PR DESCRIPTION
**Pull request by GryPr**
Formatted the README.md as in #8

### CODE REVIEW

**Review by AliZ786 — APPROVED** [review]
Everything seems to be done properly

**Review by salehatrq — COMMENTED** [review]
Good work.

**Review by salehatrq — APPROVED** [review]

**Review by bhattirahat — APPROVED** [review]
Good work nicely done

**Review by ZahinK7 — APPROVED** [review]
Looks good

**Review by Romdefaz — APPROVED** [review]

**Review by Romdefaz — APPROVED** [review]
looks fine!

**Review by ChristopherKhoury — APPROVED** [review]
perfect

**Pull request merged**
