### PR TITLE
Issue #85

### PR DESCRIPTION
**Pull request by AliZ786**
Please check the CSS properly and leave comments (need to run both frontend and backend at the same time)

### CODE REVIEW

**Comment by GryPr** [comment]
Features seem to work well. When you have time, could you fix the warnings produced by the linter (some of them maybe were caused by code that I helped add yesterday)?

Otherwise, it's good to merge. The CSS doesn't seem to be a massive issue, but if you want to further refine the aesthetics, you can do so if there's enough time towards the end of the sprint by opening a new github issue.

image

**Review by GryPr — APPROVED** [review]
Looks good to me!

**Review by bhattirahat — APPROVED** [review]
good work

**Comment by GryPr** [comment]
@AliZ786 Whenever you're ready, you can merge the changes 👍

**Pull request merged**
