### PR TITLE
Sprint 2 #53 #52 #48 #45 #44 #43 #34 #32 #21 #18

### LINKED ISSUE #18: User Story #2: As a user, I want to have a main page that displays everyone's images
Priority: High
Risk: Low
Story Points: 8

## Description
"As a user, I want to have a front page that contains content from other users that I can browse"

When going to the top level of the website, the user should be able to see a feed of posts from all the users

## Steps
* Add list of posts
* Create post "box" component (refer to the real instagram's main page, each post has a box where there's the image, like buttons, and a comment box)

## Tasks
* #40 - MongoDB connection in the backend
* #33 - Create API backend
* #48 - Design main page components
* #32 - Image box component
* #45 - Consume form-data from React

### LINKED ISSUE #21: User Story #3: As a user, I want to be able to post images
Priority: High
Risk: Medium
Story Points: 8

## Description
"As a user, I want to be able to post images for others to view"

The user should be able to post images that appear under their profile

## Steps
* Add post image button
* Add image upload box
* Add API that receives the image data from the frontend
* Add database access that uploads the image

## Tasks
* #34 - Consume authenticated API in React
* #44 - React image upload
* #40 - MongoDB connection in the backend
* #33 - Create API backend

### LINKED ISSUE #32: Image box/post component
It would be like the boxes on the Instagram front page

You can use placeholder text and images, we're mostly concerned with having a "template/format" created

Example: 
image

It should have the following:
- Name of the poster
- Image
- Description

### LINKED ISSUE #34: Consume an authenticated API in React using fetch
Look into fetch/call methods in React.

Create a test repo (where you do your experiments) with React on Github and post it here too.

References:
https://www.smashingmagazine.com/2020/06/rest-api-react-fetch-axios/
or other references you can find on consuming APIs from React

### LINKED ISSUE #44: Implement image upload to React
~~`The website should take in an image upload, and convert it to a "byte" type variable. This will then be sent inside a JSON to the backend API.~~

2021/02/17 Update:
**Description**
The API backend currently expect form-data as described here: https://github.com/GryPr/SOEN341/issues/40#issuecomment-779582335

We need to find a way to receive an image from the user through an upload button (or drag & drop), then send the image data + description to the backend using form-data.

**Objectives**
* Create code to send image files to the backend through form-data instead of JSON
* Once the API backend is complete, integrate your code with the API

**References**
~~https://stackoverflow.com/questions/40794468/upload-a-image-with-fetch~~
https://mattboldt.com/2020/05/02/formdata-with-react-hooks-and-fetch/

### LINKED ISSUE #45: Consume byte array from an API in React using fetch
**Description**
We need to consume form-data instead of JSON when receiving images through an API. This is slightly unconventional, but it seems to be the best way to do things.

**Objectives**
- Create code to consume form-data that contains both text and files (images) from within React. 
- Display the images received from form-data on the website
- Once the API backend is complete, integrate it into the website. 

**References**
This link describes sending form-data, but not necessarily receiving it. Though it should be possible to get a formdata object from the API response: https://mattboldt.com/2020/05/02/formdata-with-react-hooks-and-fetch/
Feel free to also try to find other reference material online to get this to work

**Update 2021/02/28**
Turns out that it's somewhat difficult for the backend API to send a form-data response to the frontend. For now, the backend sends a JSON to the frontend that contains a byte array with the image data.

Information and data types in the JSON:
```c#
public string FileName { get; set; } // i.e. image.jpg or image.png
public string ContentType { get; set; } // i.e. image/jpeg
public string ImageDescription { get; set; }
public DateTime CreatedOn { get; set; }
public string CreatorName { get; set; }
public byte[] ImageContent { get; set; }
```

### LINKED ISSUE #48: Design main page components
- Create an area that would contain the image boxes

> The image boxes would be bound inside that area of the page

- Create code that would display a one or two column grid with images from a list/array of types

> The list/array would contain all the necessary data to pass to the props of the image box component. You can use the map function to create a box component for each element in the list/array

http://www.hackingwithreact.com/read/1/13/rendering-an-array-of-data-with-map-and-jsx

### PR DESCRIPTION
**Pull request by GryPr**
Finalized code for sprint 2
Closes #48 
Closes #45 
Closes #44 
Closes #34 
Closes #32 
Closes #21 
Closes #18

### CODE REVIEW

**Review by bhattirahat — APPROVED** [review]
Great work

**Review by salehatrq — APPROVED** [review]
Looks good!

**Review by AliZ786 — APPROVED** [review]
Well done

**Review by ChristopherKhoury — COMMENTED** [review]
Great job

**Pull request merged**
